// esbuild.config.mjs
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\nZoro Obsidian Plugin - bundled file\nIf you see errors here, run 'npm run build' from the plugin source\n*/`;

const prod = process.argv.includes("production") || process.argv.includes("--production");

const ctx = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  platform: "node",
  format: "cjs",
  external: ["obsidian", ...builtins],
  sourcemap: prod ? false : "inline",
  banner: { js: banner },
  target: ["es2018"],
  outfile: "main.js",
  minify: prod,
  legalComments: "none"
});

if (prod) {
  // one-shot production build
  await ctx.rebuild();
  await ctx.dispose();
  console.log("esbuild: production build complete -> main.js");
  process.exit(0);
} else {
  // dev/watch
  console.log("esbuild: starting watch (dev) - press CTRL+C to stop");
  await ctx.watch();
}